version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r ci-cd/app/requirements.txt

  build:
    commands:
      - echo "Running tests..."
      - cd ci-cd/app
      - pytest tests/

artifacts:
  files:
    - ci-cd/app/main.py
    - ci-cd/app/requirements.txt
    - ci-cd/appspec.yml
    - ci-cd/scripts/restart.sh
    - ci-cd/scripts/validate.sh
